import os

PATH_FOR_ASSETS = os.getcwd() + '/assets'

SPRITE_SCALING_PLAYER = 0.5
SPRITE_SCALING_ALIEN = 0.2
SPRITE_SCALING_LASER = 0.8
ALIEN_COUNT = 50

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

BULLET_SPEED = 5

PATH_TO_MYSHIP = PATH_FOR_ASSETS+"/space_shooter/PNG/playerShip1_blue.png"
PATH_TO_ALIEN  = PATH_FOR_ASSETS+"/space_shooter/PNG/ufoYellow.png"
PATH_TO_BULLET = PATH_FOR_ASSETS+"/space_shooter/PNG/Lasers/laserRed01.png"

